include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_expression_function_bodies: true
    avoid_print: false
    prefer_final_locals: true
    prefer_final_fields: true

dart_style:
  code_width: 80
  indent: 2
